---
- hosts: webservers
  become: yes
  become_method: sudo
  remote_user: runner

  tasks:
  - name: Install Nmap
    apt:
      name: nmap
      state: latest
      update_cache:  yes

  - name: Copy Nmap targets list
    copy:
      src: ./targets.txt
      dest: ~/targets_2.txt
      force: yes
      mode: '0644'

  - name: Run Nmap
    shell: "nmap -iL ~/targets_2.txt -p 80 -oG -"
    register: nmap_result

  - name: Nmap output
    debug:
      msg: "{{ nmap_result.stdout_lines }}"
